# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Linux

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  linux:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3

      - uses: SwiftyLab/setup-swift@latest

      - name: Get swift version
        run: swift --version

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test
